import type { Metadata } from "next";
import "./globals.css";
import { Anta } from "next/font/google";

export const metadata: Metadata = {
  title: "SuperDM",
  description: "Generated by create next app",
};

const anta = Anta({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` bg-black  w-5/6 mx-auto ${anta.className}`}>
        {children}
      </body>
    </html>
  );
}
