import type { Metadata } from "next";
import "./globals.css";
import Appbar from "./_components/Appbar";

export const metadata: Metadata = {
  title: "SuperDM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-mono bg-black h-full w-5/6 mx-auto">
        <Appbar />
        {children}
      </body>
    </html>
  );
}
